# ntp setup and configuration.
---

- name: Copy ntp config
  template:
    src: "ntp.conf.j2"
    dest: "/etc/ntp.conf"
  notify: restart ntp
  tags: [ "config", "package", "ntp" ]

- name: Make sure ntp daemon is enabled to start after boot
  service:
    name: "{{ time_ntp_daemon_name }}"
    enabled: yes
    pattern: "/ntpd"
  tags: [ "service", "ntp" ]
